quarkus.swagger-ui.always-include=true
quarkus.datasource.db-kind=postgresql
mp.jwt.verify.issuer=${OFICINA_AUTH_ISSUER:oficina-api}
mp.jwt.verify.audiences=${OFICINA_AUTH_AUDIENCE:oficina-app}

%dev.quarkus.hibernate-orm.schema-management.strategy = drop-and-create
%dev.quarkus.hibernate-orm.sql-load-script=import.sql
%dev.quarkus.datasource.devservices.port=32771
%dev.quarkus.mailer.from=noreply@oficina.local
%dev.quarkus.mailer.mock=true
%dev.mp.jwt.verify.publickey.location=${MP_JWT_VERIFY_PUBLICKEY_LOCATION:file:src/main/resources/jwt/publicKey.pem}
%dev.smallrye.jwt.sign.key.location=${SMALLRYE_JWT_SIGN_KEY_LOCATION:file:src/main/resources/jwt/privateKey.pem}

%test.quarkus.hibernate-orm.schema-management.strategy = drop-and-create
%test.quarkus.hibernate-orm.sql-load-script=import.sql
%test.quarkus.test.integration-test-profile=test
%test.quarkus.mailer.from=noreply@oficina.test
%test.quarkus.mailer.mock=true
%test.mp.jwt.verify.publickey.location=classpath:test-jwt/publicKey.pem
%test.smallrye.jwt.sign.key.location=classpath:test-jwt/privateKey.pem
#%test.quarkus.datasource.devservices.port=32772

%prod.mp.jwt.verify.issuer=${OFICINA_AUTH_ISSUER}
%prod.mp.jwt.verify.publickey.location=${MP_JWT_VERIFY_PUBLICKEY_LOCATION}
