apiVersion: v1
kind: ConfigMap
metadata:
  name: oficina-app-config
  labels:
    app.kubernetes.io/name: oficina-app
    app.kubernetes.io/part-of: oficina
data:
  JAVA_TOOL_OPTIONS: -Dquarkus.hibernate-orm.schema-management.strategy=update
  OFICINA_AUTH_ISSUER: OFICINA_AUTH_ISSUER_PLACEHOLDER
  OFICINA_AUTH_AUDIENCE: oficina-app
  MP_JWT_VERIFY_PUBLICKEY_LOCATION: OFICINA_AUTH_JWKS_URI_PLACEHOLDER
